Repository INSOPT-CDS-Behance/server, pull requests merged in 2022-11, with the labels that each got.

#3 [Chore] Project Setting
  .gitignore
  cds-server/nodemon.json
  cds-server/package.json
  cds-server/src/controller/index.ts
  cds-server/src/controller/likeController.ts
  cds-server/src/controller/moodboardController.ts
  cds-server/src/controller/projectController.ts
  cds-server/src/index.ts
  cds-server/src/router/index.ts
  cds-server/src/router/likeRouter.ts
  cds-server/src/router/moodboardRouter.ts
  cds-server/src/router/projectRouter.ts
  cds-server/src/service/index.ts
  cds-server/src/service/likeService.ts
  cds-server/src/service/moodboardService.ts
  cds-server/src/service/projectService.ts
  cds-server/tsconfig.json
  cds-server/yarn.lock
  package-lock.json
  package.json
  prisma/schema.prisma
  yarn.lock
Labels: 혜윤, PR

#6 [Chore] prisma db pull (#5)
  prisma/schema.prisma
Labels: 혜윤, PR

#7 [Chore] Response Message, Status Code 추가
  cds-server/src/constants/responseMessage.ts
  cds-server/src/constants/statusCode
Labels: 혜수, PR

#13 [Chore] constants, interfaces 폴더 추가
  cds-server/src/constants/index.ts
  cds-server/src/constants/response.ts
  cds-server/src/constants/responseMessage.ts
  cds-server/src/constants/statusCode.ts
Labels: 혜윤, PR

#14 [Feat] moodboardGetAPI (#11)
  cds-server/package.json
  cds-server/prisma/schema.prisma
  cds-server/src/constants/responseMessage.ts
  cds-server/src/controller/moodboardController.ts
  cds-server/src/router/moodboardRouter.ts
  cds-server/src/service/moodboardService.ts
  cds-server/yarn.lock
Labels: 혜윤, PR

#16 [Feat] moodboardPatchAPI (#15)
  cds-server/src/constants/responseMessage.ts
  cds-server/src/constants/statusCode.ts
  cds-server/src/controller/moodboardController.ts
  cds-server/src/interfaces/moodboard/MoodboardPatchDTO.ts
  cds-server/src/router/moodboardRouter.ts
  cds-server/src/service/moodboardService.ts
Labels: Feat, 혜윤

#17 [Feat] post 좋아요 api 구현 (#9)
  cds-server/src/constants/responseMessage.ts
  cds-server/src/controller/likeController.ts
  cds-server/src/router/index.ts
  cds-server/src/router/likeRouter.ts
  cds-server/src/service/likeService.ts
Labels: Feat, 예린

#21 [Feat] 프로젝트 목록 조회 api 구현
  cds-server/src/constants/responseMessage.ts
  cds-server/src/controller/projectController.ts
  cds-server/src/router/projectRouter.ts
  cds-server/src/service/projectService.ts
Labels: 혜수, PR

#22 [Feat] 프로젝트 상세조회 (#20)
  cds-server/src/constants/responseMessage.ts
  cds-server/src/controller/projectController.ts
  cds-server/src/index.ts
  cds-server/src/router/projectRouter.ts
  cds-server/src/service/projectService.ts
Labels: 혜수, PR

#24 [Fix] addTryCatch (#23)
  cds-server/src/controller/moodboardController.ts
  cds-server/src/service/moodboardService.ts
Labels: 혜윤, PR

#26 [fix] addTryCatch (#25)
  cds-server/src/constants/responseMessage.ts
  cds-server/src/controller/likeController.ts
  cds-server/src/service/likeService.ts
Labels: Fix, 예린

#28 [Feat] project detail API 에러처리 추가 (#27)
  cds-server/src/controller/projectController.ts
Labels: 혜수, PR

#32 [Fix] MbGetAPI_add Data
  cds-server/prisma/schema.prisma
Labels: 혜윤, PR
